CREATE TABLE EMPLOYEE
(
	EMPLOYEE_ID BIGINT NOT NULL,
	EMPLOYEE_NAME TEXT NOT NULL,
	MANAGER_ID BIGINT,
	CONSTRAINT PK_EMPLOYEE_ID PRIMARY KEY (EMPLOYEE_ID)
);


INSERT INTO EMPLOYEE(EMPLOYEE_ID, EMPLOYEE_NAME, MANAGER_ID) VALUES (1, 'Eusebio Garlock', null);
INSERT INTO EMPLOYEE(EMPLOYEE_ID, EMPLOYEE_NAME, MANAGER_ID) VALUES (2, 'Shamika Linderman', 1);
INSERT INTO EMPLOYEE(EMPLOYEE_ID, EMPLOYEE_NAME, MANAGER_ID) VALUES (3, 'Onie Cresswell', 1);
INSERT INTO EMPLOYEE(EMPLOYEE_ID, EMPLOYEE_NAME, MANAGER_ID) VALUES (4, 'In Smit', 1);
INSERT INTO EMPLOYEE(EMPLOYEE_ID, EMPLOYEE_NAME, MANAGER_ID) VALUES (5, 'Rigoberto Dunnam', null);
INSERT INTO EMPLOYEE(EMPLOYEE_ID, EMPLOYEE_NAME, MANAGER_ID) VALUES (6, 'Cherilyn Gossman', 5);
INSERT INTO EMPLOYEE(EMPLOYEE_ID, EMPLOYEE_NAME, MANAGER_ID) VALUES (7, 'Nola Mcmillen', 5);
INSERT INTO EMPLOYEE(EMPLOYEE_ID, EMPLOYEE_NAME, MANAGER_ID) VALUES (8, 'Emanuel Burlew', 5);
INSERT INTO EMPLOYEE(EMPLOYEE_ID, EMPLOYEE_NAME, MANAGER_ID) VALUES (9, 'Paula Breiner', 5);
INSERT INTO EMPLOYEE(EMPLOYEE_ID, EMPLOYEE_NAME, MANAGER_ID) VALUES (10, 'Nydia Windsor', null);
INSERT INTO EMPLOYEE(EMPLOYEE_ID, EMPLOYEE_NAME, MANAGER_ID) VALUES (11, 'Roselle Sheffler', 10);
INSERT INTO EMPLOYEE(EMPLOYEE_ID, EMPLOYEE_NAME, MANAGER_ID) VALUES (12, 'Julia Borden', 10);
INSERT INTO EMPLOYEE(EMPLOYEE_ID, EMPLOYEE_NAME, MANAGER_ID) VALUES (13, 'Herschel Blackwood', 10);
INSERT INTO EMPLOYEE(EMPLOYEE_ID, EMPLOYEE_NAME, MANAGER_ID) VALUES (14, 'Genevie Elson', 10);
INSERT INTO EMPLOYEE(EMPLOYEE_ID, EMPLOYEE_NAME, MANAGER_ID) VALUES (15, 'Rossana Vogel', null);
INSERT INTO EMPLOYEE(EMPLOYEE_ID, EMPLOYEE_NAME, MANAGER_ID) VALUES (16, 'Lashon Goodell', 15);
INSERT INTO EMPLOYEE(EMPLOYEE_ID, EMPLOYEE_NAME, MANAGER_ID) VALUES (17, 'Lashandra Shur', 15);
INSERT INTO EMPLOYEE(EMPLOYEE_ID, EMPLOYEE_NAME, MANAGER_ID) VALUES (18, 'Sharyn Cazarez', 15);
INSERT INTO EMPLOYEE(EMPLOYEE_ID, EMPLOYEE_NAME, MANAGER_ID) VALUES (19, 'Carita Norsworthy', 15);
INSERT INTO EMPLOYEE(EMPLOYEE_ID, EMPLOYEE_NAME, MANAGER_ID) VALUES (20, 'Jamar Tabarez', 15);

SELECT 
	employee.employee_name AS manager_name
FROM employee employee
	INNER JOIN employee manager ON manager.manager_id = employee.employee_id
GROUP BY employee.employee_name
ORDER BY employee.employee_name ASC

/*
Expected result

	Eusebio Garlock
	Nydia Windsor
	Rigoberto Dunnam
	Rossana Vogel
*/