/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ca.agranee.task02.ui;

import ca.agranee.task02.chat.ChatClientThread;
import ca.agranee.task02.chat.ChatServer;
import ca.agranee.task02.chat.ChatServerThread;
import static ca.agranee.task02.chat.ChatServerThread.USER_NAME;
import java.io.DataInputStream;
import java.io.DataOutputStream;
import java.io.IOException;
import java.net.Socket;
import java.net.UnknownHostException;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author MoreiraP
 */
public class ChatClient extends javax.swing.JFrame {

    private Socket socket = null;
    private DataInputStream console = null;
    private DataOutputStream streamOut = null;
    private ChatClientThread client = null;

    /**
     * Creates new form ClientSwing
     */
    public ChatClient() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        JTHost = new javax.swing.JTextField();
        JTPort = new javax.swing.JTextField();
        JTUser = new javax.swing.JTextField();
        JBConnect = new javax.swing.JButton();
        JTMessage = new javax.swing.JTextField();
        JBSend = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        JTADisplay = new javax.swing.JTextArea();
        JBDisconnect = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        JTAUser = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Client Chat");

        JTHost.setText("localhost");
        JTHost.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTHostActionPerformed(evt);
            }
        });

        JTPort.setText("8080");
        JTPort.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTPortActionPerformed(evt);
            }
        });

        JBConnect.setText("Connect");
        JBConnect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBConnectActionPerformed(evt);
            }
        });

        JTMessage.setEnabled(false);

        JBSend.setText("Send");
        JBSend.setEnabled(false);
        JBSend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBSendActionPerformed(evt);
            }
        });

        jLabel1.setText("Host");

        jLabel2.setText("Port");

        jLabel3.setText("User Name");

        jLabel4.setText("Connected Users");

        JTADisplay.setColumns(20);
        JTADisplay.setRows(5);
        JTADisplay.setEnabled(false);
        jScrollPane1.setViewportView(JTADisplay);

        JBDisconnect.setText("Disconnect");
        JBDisconnect.setEnabled(false);
        JBDisconnect.setPreferredSize(new java.awt.Dimension(57, 23));
        JBDisconnect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBDisconnectActionPerformed(evt);
            }
        });

        JTAUser.setColumns(20);
        JTAUser.setRows(5);
        jScrollPane2.setViewportView(JTAUser);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JTMessage)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(JTHost, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(JTUser))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(JTPort)
                                .addComponent(JBConnect, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE))))
                    .addComponent(jScrollPane1))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4)
                    .addComponent(JBDisconnect, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(JBSend, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JBDisconnect, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JTHost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JTPort, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JTUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JBConnect))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(JTMessage))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(JBSend, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JTPortActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTPortActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTPortActionPerformed

    private void JTHostActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTHostActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTHostActionPerformed

    private void JBConnectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBConnectActionPerformed

        String userName = JTUser.getText().trim();
        String host = JTHost.getText().trim();
        String portString = JTPort.getText();
        int port = Integer.parseInt(portString);

        if ((userName != null && !userName.equalsIgnoreCase(""))
                && (host != null && !host.equalsIgnoreCase(""))
                && (portString != null && !portString.equalsIgnoreCase(""))) {

            connect(host, port);
            send(String.format("%s %s", ChatServerThread.USER_NAME, userName));
            send(ChatServerThread.CONNECT);

            JBDisconnect.setEnabled(true);
            JBSend.setEnabled(true);
            JTMessage.setEnabled(true);

            JTHost.setEnabled(false);
            JTPort.setEnabled(false);
            JTUser.setEnabled(false);
            JBConnect.setEnabled(false);

        } else {

            String errorMsg = "Fields User Name, Host and Port are required.";
            
            JOptionPane.showMessageDialog(new JFrame(), errorMsg, "Dialog",
                    JOptionPane.ERROR_MESSAGE);
            
        }

    }//GEN-LAST:event_JBConnectActionPerformed

    private void JBDisconnectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBDisconnectActionPerformed
        // TODO add your handling code here:

        send(ChatServerThread.DISCONNECT);
        
        JTAUser.setText(null);
        
        JBDisconnect.setEnabled(false);
        JBSend.setEnabled(false);
        JTMessage.setEnabled(false);

        JTHost.setEnabled(true);
        JTPort.setEnabled(true);
        JTUser.setEnabled(true);
        JBConnect.setEnabled(true);

    }//GEN-LAST:event_JBDisconnectActionPerformed

    private void JBSendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBSendActionPerformed
        // TODO add your handling code here:

        String msg = JTMessage.getText().trim();

        if (msg != null && !msg.equalsIgnoreCase("")) {
            send(String.format("%s %s", ChatServerThread.MESSAGE, msg));

            JTMessage.setText(null);
        } else {

            String errorMsg = "Fields User Name, Host and Port are required.";

            JOptionPane.showMessageDialog(new JFrame(), errorMsg, "Dialog",
                    JOptionPane.ERROR_MESSAGE);

        }

    }//GEN-LAST:event_JBSendActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChatClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChatClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChatClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChatClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ChatClient().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBConnect;
    private javax.swing.JButton JBDisconnect;
    private javax.swing.JButton JBSend;
    private javax.swing.JTextArea JTADisplay;
    private javax.swing.JTextArea JTAUser;
    private javax.swing.JTextField JTHost;
    private javax.swing.JTextField JTMessage;
    private javax.swing.JTextField JTPort;
    private javax.swing.JTextField JTUser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables

    public void connect(String serverName, int serverPort) {
        try {
            socket = new Socket(serverName, serverPort);
            open();
        } catch (UnknownHostException uhe) {
            println("Host unknown: " + uhe.getMessage());
        } catch (IOException ioe) {
            println("Unexpected exception: " + ioe.getMessage());
        }
    }

    private void send(String msg) {
        try {
            streamOut.writeUTF(msg);
            streamOut.flush();
        } catch (IOException ioe) {
            println("Sending error: " + ioe.getMessage());
            close();
        }
    }

    public void handle(String msg) {
        if (msg.startsWith(ChatServer.LOGGED_USER)) {
            
            String users = msg.replace(ChatServer.LOGGED_USER, "")
                    .replace(";", "\n").trim();
            
            JTAUser.setText(users);
        } else {
            println(msg);
        }
    }

    public void open() {
        try {
            streamOut = new DataOutputStream(socket.getOutputStream());
            client = new ChatClientThread(this, socket);
        } catch (IOException ioe) {
            println("Error opening output stream: " + ioe);
        }
    }

    public void close() {

        try {

            if (streamOut != null) {
                streamOut.close();
            }
            if (socket != null) {
                socket.close();
            }

            println("Disconnect: " + client.getId());

        } catch (IOException ioe) {
            println("Error closing ...");
        }

        client.close();
        client.stop();
    }

    private void println(String msg) {

        JTADisplay.setText(JTADisplay.getText() + msg + "\n");
    }

}
